# ===== DB local =====
DB_URL=jdbc:postgresql://localhost:5432/gestao_foi
DB_USERNAME=postgres
DB_PASSWORD=31069946jm

# ===== Email  =====

MAIL_FROM=josemiguelvieira50@gmail.com
MAIL_FROM_NAME=Gestão Financeira

# ===== JWT local =====
JWT_SECRET=bWlndWVsLWdlc3Rhby1maW5hbmNlaXJhMi1qd3Qtc2VjcmV0LWtleS1tYWlzLWZvcg==
JWT_EXPIRATION_MS=86400000
JWT_CLOCK_SKEW_SECONDS=30
